// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniCinema.Data;

#nullable disable

namespace MiniCinema.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20260531123928_FixMovieTable")]
    partial class FixMovieTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MiniCinema.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfTickets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MiniCinema.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Description = "Large bucket of golden butter popcorn",
                            ImageUrl = "/images/popcorn-classic.png",
                            IsAvailable = true,
                            IsBestSeller = true,
                            Name = "Classic Butter Popcorn",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "Sweet caramel glazed popcorn",
                            ImageUrl = "/images/caramel.png",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Caramel Popcorn",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Description = "Hot chili seasoned popcorn for spice lovers",
                            ImageUrl = "/images/spicy.png",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Spicy Popcorn",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Description = "Chilled Coca-Cola 750ml",
                            ImageUrl = "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400",
                            IsAvailable = true,
                            IsBestSeller = true,
                            Name = "Coca-Cola Large",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Description = "Freshly squeezed orange juice",
                            ImageUrl = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Fresh Orange Juice",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            Description = "Large popcorn + Large drink",
                            ImageUrl = "https://images.unsplash.com/photo-1585647347483-22b66260dfff?w=400",
                            IsAvailable = true,
                            IsBestSeller = true,
                            Name = "Classic Combo",
                            Price = 8.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            Description = "2 Large popcorns + 4 drinks + nachos",
                            ImageUrl = "https://images.unsplash.com/photo-1516195851888-6f1a981a862e?w=400",
                            IsAvailable = true,
                            IsBestSeller = true,
                            Name = "Family Combo",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            Description = "Crispy nachos with warm cheese dip",
                            ImageUrl = "https://images.unsplash.com/photo-1531749668029-2db88e4276c7?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Nachos with Cheese",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 11,
                            Category = 4,
                            Description = "Creamy vanilla soft serve",
                            ImageUrl = "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Vanilla Ice Cream",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 12,
                            Category = 4,
                            Description = "Warm fudgy chocolate brownie",
                            ImageUrl = "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Chocolate Brownie",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 13,
                            Category = 0,
                            Description = "Cheddar cheese dusted popcorn — savory and addictive",
                            ImageUrl = "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Cheese Popcorn",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 14,
                            Category = 0,
                            Description = "Half butter, half caramel — best of both worlds",
                            ImageUrl = "https://images.unsplash.com/photo-1576186726115-4d51596775d1?w=400",
                            IsAvailable = true,
                            IsBestSeller = true,
                            Name = "Mix Popcorn Bucket",
                            Price = 7.00m
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            Description = "Freshly made lemonade served over ice",
                            ImageUrl = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Iced Lemonade",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 16,
                            Category = 1,
                            Description = "500ml chilled sparkling mineral water",
                            ImageUrl = "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Mineral Water",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            Description = "Rich creamy hot chocolate with marshmallows",
                            ImageUrl = "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Hot Chocolate",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 18,
                            Category = 3,
                            Description = "Crispy golden chicken nuggets with dipping sauce",
                            ImageUrl = "https://images.unsplash.com/photo-1562967914-608f82629710?w=400",
                            IsAvailable = true,
                            IsBestSeller = true,
                            Name = "Chicken Nuggets (6 pcs)",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 19,
                            Category = 3,
                            Description = "Classic beef hot dog in a toasted bun with ketchup & mustard",
                            ImageUrl = "https://images.unsplash.com/photo-1612392062631-94c93765e3d3?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Hot Dog",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 20,
                            Category = 3,
                            Description = "Warm soft pretzel bites served with cheese dip",
                            ImageUrl = "https://images.unsplash.com/photo-1639561073-8c74a6b3dbb9?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Pretzel Bites",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 21,
                            Category = 3,
                            Description = "Crispy fried mozzarella sticks with marinara sauce",
                            ImageUrl = "https://images.unsplash.com/photo-1548340748-6d2b7d7da280?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Mozzarella Sticks",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 22,
                            Category = 2,
                            Description = "Large popcorn + 2 drinks + Nachos — perfect for two",
                            ImageUrl = "https://images.unsplash.com/photo-1516195851888-6f1a981a862e?w=400",
                            IsAvailable = true,
                            IsBestSeller = true,
                            Name = "Premium Combo",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 23,
                            Category = 2,
                            Description = "Small popcorn + juice box + chocolate brownie",
                            ImageUrl = "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Kids Combo",
                            Price = 9.00m
                        },
                        new
                        {
                            Id = 24,
                            Category = 4,
                            Description = "Vanilla soft serve topped with fresh strawberry sauce",
                            ImageUrl = "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=400",
                            IsAvailable = true,
                            IsBestSeller = false,
                            Name = "Strawberry Sundae",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 25,
                            Category = 4,
                            Description = "Golden fried churros dusted with cinnamon sugar, served with chocolate dip",
                            ImageUrl = "https://images.unsplash.com/photo-1593441895-4ca2cc844b7d?w=400",
                            IsAvailable = true,
                            IsBestSeller = true,
                            Name = "Churros (4 pcs)",
                            Price = 5.50m
                        });
                });

            modelBuilder.Entity("MiniCinema.Models.FoodOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodOrders");
                });

            modelBuilder.Entity("MiniCinema.Models.FoodOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("FoodOrderId");

                    b.ToTable("FoodOrderItems");
                });

            modelBuilder.Entity("MiniCinema.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Has4K")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDolbyAtmos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasReclinerSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PremiumSurcharge")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 80,
                            Description = "Classic cinema experience with comfortable seats.",
                            Has4K = false,
                            HasDolbyAtmos = false,
                            HasReclinerSeats = false,
                            ImageUrl = "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600",
                            IsActive = true,
                            Name = "Standard Hall A",
                            PremiumSurcharge = 0m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Description = "Luxury recliner seats with Dolby Atmos surround sound and 4K projection.",
                            Has4K = true,
                            HasDolbyAtmos = true,
                            HasReclinerSeats = true,
                            ImageUrl = "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600",
                            IsActive = true,
                            Name = "Premium Hall B",
                            PremiumSurcharge = 8.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 120,
                            Description = "The ultimate IMAX experience with massive screen, laser projection, and immersive 12-channel sound.",
                            Has4K = true,
                            HasDolbyAtmos = true,
                            HasReclinerSeats = false,
                            ImageUrl = "https://images.unsplash.com/photo-1596776900519-6a37e2c44748?w=600",
                            IsActive = true,
                            Name = "IMAX Hall C",
                            PremiumSurcharge = 12.00m,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 30,
                            Description = "VIP private lounge with fully reclining seats, personal service, and 4K screen.",
                            Has4K = true,
                            HasDolbyAtmos = true,
                            HasReclinerSeats = true,
                            ImageUrl = "https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=600",
                            IsActive = true,
                            Name = "Premium Hall D",
                            PremiumSurcharge = 15.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 100,
                            Description = "Our largest standard hall with tiered seating and a wide HD screen — perfect for blockbuster nights.",
                            Has4K = false,
                            HasDolbyAtmos = false,
                            HasReclinerSeats = false,
                            ImageUrl = "https://images.unsplash.com/photo-1460881680858-30d872d5b530?w=600",
                            IsActive = true,
                            Name = "Standard Hall E",
                            PremiumSurcharge = 0m,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 150,
                            Description = "Our second IMAX hall with an even larger screen and enhanced 4D seating for a fully immersive experience.",
                            Has4K = true,
                            HasDolbyAtmos = true,
                            HasReclinerSeats = false,
                            ImageUrl = "https://images.unsplash.com/photo-1596776900519-6a37e2c44748?w=600",
                            IsActive = true,
                            Name = "IMAX Hall F",
                            PremiumSurcharge = 12.00m,
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 20,
                            Description = "Ultra-exclusive 20-seat boutique hall with personal butler service, gourmet menu, and 4K laser screen.",
                            Has4K = true,
                            HasDolbyAtmos = true,
                            HasReclinerSeats = true,
                            ImageUrl = "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600",
                            IsActive = true,
                            Name = "Premium Hall G",
                            PremiumSurcharge = 20.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 60,
                            Description = "A cozy mid-size hall ideal for indie films, special screenings, and private events.",
                            Has4K = true,
                            HasDolbyAtmos = false,
                            HasReclinerSeats = false,
                            ImageUrl = "https://images.unsplash.com/photo-1507924538820-ede94a04019d?w=600",
                            IsActive = true,
                            Name = "Standard Hall H",
                            PremiumSurcharge = 0m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("MiniCinema.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A skilled thief enters dreams to steal secrets and plant ideas.",
                            Director = "Christopher Nolan",
                            DurationMinutes = 148,
                            Genre = "Sci-Fi",
                            IsActive = true,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
                            Rating = 8.8000000000000007,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Cast = "Matthew McConaughey, Anne Hathaway",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A group of explorers travel through space to save humanity.",
                            Director = "Christopher Nolan",
                            DurationMinutes = 169,
                            Genre = "Sci-Fi",
                            IsActive = true,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                            Rating = 8.6999999999999993,
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            Cast = "Christian Bale, Heath Ledger",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Batman faces the Joker, a criminal mastermind spreading chaos.",
                            Director = "Christopher Nolan",
                            DurationMinutes = 152,
                            Genre = "Action",
                            IsActive = true,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            Rating = 9.0,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        });
                });

            modelBuilder.Entity("MiniCinema.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplicableHallType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColor = "info",
                            Description = "20% off all tickets every Tuesday. Valid student ID required at the counter.",
                            DiscountValue = 20m,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsActive = true,
                            PromoCode = "STUDENT20",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Student Tuesday Deal",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ApplicableHallType = 2,
                            BadgeColor = "primary",
                            Description = "Book 2 IMAX tickets and get $5 off your total. Weekends only.",
                            DiscountValue = 5m,
                            EndDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsActive = true,
                            PromoCode = "IMAXWEEKEND",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "IMAX Weekend Special",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            ApplicableHallType = 0,
                            BadgeColor = "success",
                            Description = "Buy one Standard ticket on Monday and get the second one absolutely free!",
                            DiscountValue = 100m,
                            EndDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsActive = true,
                            PromoCode = "BOGO",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Buy 1 Get 1 Free — Mondays",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            ApplicableHallType = 1,
                            BadgeColor = "warning",
                            Description = "2 Premium tickets + 2 drinks + 1 popcorn combo at a special bundled price.",
                            DiscountValue = 15m,
                            EndDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsActive = true,
                            PromoCode = "DATENITE",
                            StartDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Premium Date Night",
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            BadgeColor = "danger",
                            Description = "4 tickets for the price of 3! Perfect for family outings.",
                            DiscountValue = 25m,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsActive = true,
                            PromoCode = "FAMILY4",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Family Pack",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            BadgeColor = "warning",
                            Description = "Enjoy 15% off any booking throughout summer. No restrictions — all halls, all days.",
                            DiscountValue = 15m,
                            EndDate = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsActive = true,
                            PromoCode = "SUMMER26",
                            StartDate = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Summer Blockbuster Pass",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            BadgeColor = "success",
                            Description = "Book any screening before 12:00 PM and save $3 on your ticket price.",
                            DiscountValue = 3m,
                            EndDate = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "",
                            IsActive = true,
                            PromoCode = "EARLYBIRD",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Early Bird Special",
                            Type = 1
                        });
                });

            modelBuilder.Entity("MiniCinema.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ShowtimeId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("MiniCinema.Models.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hall")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HallId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ShowDateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 60,
                            Hall = "Hall A",
                            HallId = 1,
                            IsActive = true,
                            MovieId = 1,
                            ShowDateTime = new DateTime(2026, 6, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 12.50m,
                            TotalSeats = 60
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 60,
                            Hall = "Hall B",
                            HallId = 2,
                            IsActive = true,
                            MovieId = 1,
                            ShowDateTime = new DateTime(2026, 6, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 15.00m,
                            TotalSeats = 60
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 60,
                            Hall = "Hall C",
                            HallId = 3,
                            IsActive = true,
                            MovieId = 2,
                            ShowDateTime = new DateTime(2026, 6, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 14.00m,
                            TotalSeats = 60
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 60,
                            Hall = "Hall A",
                            HallId = 1,
                            IsActive = true,
                            MovieId = 3,
                            ShowDateTime = new DateTime(2026, 6, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 16.00m,
                            TotalSeats = 60
                        });
                });

            modelBuilder.Entity("MiniCinema.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@minicinema.com",
                            FullName = "Admin",
                            IsAdmin = true,
                            PasswordHash = "a8c0FSuYbAljQVFfcAQ5i/APfHmGAjviYalifjtzw+U="
                        });
                });

            modelBuilder.Entity("MiniCinema.Models.Booking", b =>
                {
                    b.HasOne("MiniCinema.Models.Showtime", "Showtime")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCinema.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniCinema.Models.FoodOrder", b =>
                {
                    b.HasOne("MiniCinema.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.HasOne("MiniCinema.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniCinema.Models.FoodOrderItem", b =>
                {
                    b.HasOne("MiniCinema.Models.FoodItem", "FoodItem")
                        .WithMany("FoodOrderItems")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCinema.Models.FoodOrder", "FoodOrder")
                        .WithMany("Items")
                        .HasForeignKey("FoodOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("FoodOrder");
                });

            modelBuilder.Entity("MiniCinema.Models.Seat", b =>
                {
                    b.HasOne("MiniCinema.Models.Booking", "Booking")
                        .WithMany("Seats")
                        .HasForeignKey("BookingId");

                    b.HasOne("MiniCinema.Models.Showtime", "Showtime")
                        .WithMany("Seats")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("MiniCinema.Models.Showtime", b =>
                {
                    b.HasOne("MiniCinema.Models.Hall", "HallDetails")
                        .WithMany("Showtimes")
                        .HasForeignKey("HallId");

                    b.HasOne("MiniCinema.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HallDetails");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MiniCinema.Models.Booking", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("MiniCinema.Models.FoodItem", b =>
                {
                    b.Navigation("FoodOrderItems");
                });

            modelBuilder.Entity("MiniCinema.Models.FoodOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MiniCinema.Models.Hall", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("MiniCinema.Models.Movie", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("MiniCinema.Models.Showtime", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("MiniCinema.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
